### ISSUE TITLE
Missing "explorer" folder

### ISSUE THREAD

**Issue by feelingdev** [eswick/osexperience#1]
Hello @eswick , good day! Sorry to bother you. I was gifted the ios 6 and ios 7 version of this tweak by you way back when ios 7 is the latest. I know that the license server is no longer in service so I am trying to recompile this tweak for my son's coolbooted ios 7.1.2. Unfortunately I found some missing dependencies..

1. explorer/OSExplorerWindow.h
2. explorer/CGPointExtension.h

.. So far, I am stuck with those missing dependencies. I read from your Readme.md that it's okay to contact you for any questions. Again, sorry to bother you. Thank you so much.

**Comment by EthanArbuckle** [comment]
Unfortunately Evan passed away in 2020
